In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df=pd.read_csv("Linear_Regression_multiple_variables.csv")
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [8]:
import math
median_bedroom=math.floor(df.bedroom.median())        #math.floor=rounds down the number to the nearest integer
median_bedroom

3

In [12]:
df.bedroom=df.bedroom.fillna(median_bedroom)                      #fillna=replaces the blank place with appropriate numbers in that particular row
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [14]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedroom','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [17]:
reg.intercept_

383724.99999999994

In [20]:
reg.predict([[3000,3,40]])

array([444400.])

In [21]:
reg.predict([[2500,4,5]])

array([588625.])